/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    java
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}


repositories {
    mavenCentral()
}

dependencies {

    testImplementation("io.github.bonigarcia:webdrivermanager:5.6.3")

    // Selenium WebDriver
    implementation("org.seleniumhq.selenium:selenium-java:4.20.0")

    // TestNG
    testImplementation("org.testng:testng:7.9.0")
}

tasks.test {
    useTestNG()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

tasks.register("stage") {
    dependsOn("build")
}